### ISSUE TITLE
error web /users/nick.cfg

### ISSUE THREAD

**Issue by zsak1** [ItsVops/Vops-Capes#11]
Hey, can you secure myadrees.com/users/Nick.cfg typing?

**Comment by zsak1** [comment]
because currently you can type e.g. myadress.com/users/zsak1.cfg and you can easily steal texture paths etc.
![unknown](https://user-images.githubusercontent.com/25277653/147343474-294ca930-2ef9-4e47-b699-31c24fe4ee37.png)

**Comment by ItsVops** [comment]
The most that can be done is require a Java header, which can be easily bypassed, so I don't think I'll be changing this.
