### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by mrpiesel** [ItsVops/Vops-Capes#3]
[prefix]info @MrPiesel

4|cape  | TypeError: Cannot read properties of null (reading 'cape')
4|cape  |     at /var/nCape/discord/commands/info.js:22:103
4|cape  |     at Query.onResult (/var/nCape/api/storage/mysql.js:47:5)
4|cape  |     at /var/nCape/node_modules/mysql2/lib/commands/query.js:86:16
4|cape  |     at processTicksAndRejections (node:internal/process/task_queues:78:11)
PM2     | App [cape:4] exited with code [1] via signal [SIGINT]

**Comment by ItsVops** [comment]
will fix in an hour (not home atm)

**Comment by mrpiesel** [comment]
okay

**Comment by ItsVops** [comment]
should be fixed. let me know
