### ISSUE TITLE
command link error bug

### ISSUE THREAD

**Issue by zsak1** [ItsVops/Vops-Capes#6]
![image](https://user-images.githubusercontent.com/25277653/143440499-e08c39a1-e72f-40d9-97e3-1ed2cb024ee6.png)

link command displays wrong entries! link Discord tag and nickname does not work

you have to enter! link Discord tag or nick

then it works

and something like this is displayed

**Comment by zsak1** [comment]
![image](https://user-images.githubusercontent.com/25277653/143440768-10070063-61e4-403e-bed3-85f4abe5430f.png)

**Comment by zsak1** [comment]
![image](https://user-images.githubusercontent.com/25277653/143440919-0e7f731b-cd09-43e6-b1a0-a27942b2489b.png)

**Comment by zsak1** [comment]
I corrected the link hold command

https://www.toptal.com/developers/hastebin/ceyucaxexu.typescript

**Comment by zsak1** [comment]
the command! info is also bugged

**Comment by zsak1** [comment]
it would be nice if you type! link
I'm writing this your account is already connected

**Comment by ItsVops** [comment]
I believe there is a language barrier here as I am somewhat confused to what you are saying.

**Comment by zsak1** [comment]
in short, the item giving is bugged

**Comment by zsak1** [comment]
I do not give items, but I do give capes

**Comment by zsak1** [comment]
!link and !info are bugged

**Comment by zsak1** [comment]
see the screenshot

**Comment by ItsVops** [comment]
I am going to close this as you cannot understand me clearly due to the language barrier. I personally do not have any issues with linking or items on their available versions

**Comment by ItsVops** [comment]
I suggest leaving the languages for the discord bot in English if you want support.
