### ISSUE TITLE
items notworking

### ISSUE THREAD

**Issue by zsak1** [ItsVops/Vops-Capes#7]
I gave myself item when I type the command
! info
I am writing that I have the item given when i run minecraft 1.8.8 optifine and there is no item, only the cape is

**Comment by ItsVops** [comment]
I believe items only work on 1.12.2+ for lunar.

**Comment by zsak1** [comment]
in command !info
there is a bug

instead of the minecraft nick, the discord nick is shown

**Comment by zsak1** [comment]
you are wrong because I corrected this bug, I managed and it works

**Comment by zsak1** [comment]
the error was in mysql.js

**Comment by ItsVops** [comment]
The bug is not shown when I test it. This is probably something you edited.![image](https://user-images.githubusercontent.com/55073114/143489103-a09ca7e7-4cb8-4aab-8e74-d6ae47cfd806.jpeg)

**Comment by zsak1** [comment]
I changed the default configuration in mysql.js to


getUserCfg (username, cb) {

  connection.query ('SELECT item from users WHERE `username` =?', [username],
  function (error, results, fields) {
let userList = JSON.parse (fs.readFileSync ('./api / users.json'));
if (! userList [username] ||! userList [username] .items);
    let obj = {items: []}
    if (! results [0] ||! results [0] .item) return cb (obj);
    obj.items.push ({
        "type": "custom",
        "model": "assets / items /" + results [0] .item + "/ model.cfg",
        "texture": "assets / items /" + results [0] .item + "/ texture.png",
        "Active": "true"
    })
    cb (obj);
  });
}


they're working

**Comment by zsak1** [comment]
https://www.toptal.com/developers/hastebin/ruwiluyazu.typescript

**Comment by ItsVops** [comment]
You created this bug as it is not shown in official Versions when using MySQL

**Comment by zsak1** [comment]
in the !info command I didn't change anything
