### ISSUE TITLE
add functions !link  the account is already connected to discord

### ISSUE THREAD

**Issue by zsak1** [ItsVops/Vops-Capes#8]
add to !link, functions,
a message that the account is already linked
when I enter this command again

and add the command !change nick

**Comment by zsak1** [comment]
it would be useful to add embed removal function after 5 sec in every command

**Comment by ItsVops** [comment]
change would be pointless, as somebody could just relink the user to their new name.
a message that the account is already linked could be added, but is minor.

**Comment by zsak1** [comment]
yes, but users will spam with this command Could use a cooldown time

**Comment by zsak1** [comment]
or make, command !change nick

**Comment by zsak1** [comment]
and then a change would be a plus, but you are right that then another user could plug in the player

**Comment by ItsVops** [comment]
users could spam, but this is a repo suggested for small groups of friends which means users usually have a level of trust for each other to not ruin free capes.

**Comment by ItsVops** [comment]
change will not be added but account is already linked will be considered or added in a future update

**Comment by zsak1** [comment]
you're right,
would you be able to do a cooldown on other commands?

**Comment by ItsVops** [comment]
will be considered

**Comment by zsak1** [comment]
and removing the embed? after some time

**Comment by ItsVops** [comment]
probably not unless more suggest

**Comment by zsak1** [comment]
in the sense that when he hands you the item, he effectively removes the embed message

**Comment by ItsVops** [comment]
it will not be added unless more people want it

**Comment by zsak1** [comment]
ok
